image: maxking/mailman-ci-runner

python2.7:
  script:
  - tox -e py27

python3.4:
  script:
  - tox -e py34
  allow_failure: true

python3.5:
  script:
  - tox -e py35
  allow_failure: true

lint:
  script:
  - tox -e lint
